# Generated by Django 4.2.5 on 2023-09-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subject.personnel",
                    ),
                ),
                ("role", models.CharField(default="Student", max_length=20)),
            ],
            bases=("subject.personnel",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "personnel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="subject.personnel",
                    ),
                ),
                ("role", models.CharField(default="Teacher", max_length=20)),
            ],
            bases=("subject.personnel",),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("title", models.CharField(max_length=64)),
                ("seat", models.IntegerField()),
                ("seat_max", models.IntegerField()),
                ("gp", models.IntegerField()),
                (
                    "class_list",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_subjects",
                        to="subject.student",
                    ),
                ),
                (
                    "host",
                    models.ManyToManyField(
                        blank=True, related_name="taught_subjects", to="subject.teacher"
                    ),
                ),
            ],
        ),
    ]
